# Generated by Django 5.1.2 on 2025-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('school', 'school'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
